name: DevQuiz
description: DevQuiz - GRC-DEV
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_fonts: any
  share_plus: ^4.0.3

dev_dependencies:
  lint: any
  flutter_lints: any
  integration_test:
    sdk: flutter
  flutter_test:
     sdk: flutter
  flutter_driver:
     sdk: flutter
  test: any

flutter:
  assets:
    - assets/images/
    - assets/database/

  uses-material-design: true